export const NOTIFICATIONS_SUBSCRIPTION_READY = 'NOTIFICATIONS_SUBSCRIPTION_READY';
export const NOTIFICATIONS_SUBSCRIPTION_CHANGED = 'NOTIFICATIONS_SUBSCRIPTION_CHANGED';
export const NOTIFICATIONS_SUBSCRIPTION = 'notifications';